# Generated by Django 4.1 on 2024-05-04 05:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parkingareanumber', models.CharField(max_length=100)),
                ('vehicletype', models.CharField(max_length=100)),
                ('vehiclelimit', models.IntegerField()),
                ('parkingharge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=True)),
                ('doc', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='add_vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=250)),
                ('vehicletype', models.CharField(max_length=200)),
                ('parkingharge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=True)),
                ('arrival_time', models.DateTimeField(default=datetime.datetime.now)),
                ('parkingareanumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application1.add_category')),
            ],
        ),
    ]
